from pico_weather_station.tasks.log_weather import LogWeather
from pico_weather_station.tasks.log_vitals import LogVitals

from pico_weather_station.tasks.log_pv_data import LogPvData

from pico_weather_station.tasks.toggle_wlan import ToggleWlan
from pico_weather_station.tasks.sync_internal_rtc import SyncInternalRTC
